### PR TITLE
Implemented rms cutoff & directly use numpy array as input image

### PR DESCRIPTION
**Pull request by jackieykma**
I've added in two functionalities to the convRHT that may be useful to others. These changes have been implemented in a backward compatible way (i.e., this new version will not affect the results that current users get from the current main branch)

**rms_cutoff**
I've implemented an rms cut to preclude the low signal-to-noise areas being erroneously identified as filamentary structures. Specifically, each bitmask pixel is forced to be False if the pixel value of the input map is less than the value of the rms_cutoff value. By default, the rms_cutoff is set as "None", which will turn off this functionality. The rms_cutoff can be set as a constant value (float or integer) applied across the entire input map, or as a map (string being the file path, or numpy array) that may suit cases where the noise level varies across the input map.

**numpy array as input image**
The current main branch takes [datafn] as the path to the input .FITS file (string). I've made it also possible to directly feed in numpy array as the input map.

Happy to discuss more on the exact implementations of these!

### CODE REVIEW

**Comment by seclark** [comment]
Hi Jackie: thank you! I've been thinking and I wonder if a more flexible version of this might be to implement a mask option, where the user could pass a mask to be applied at the bitmask stage. Could be more flexible if a user wants to specify excluded pixels based on something more complicated than a single-value cutoff. What do you think?

**Comment by jackieykma** [comment]
Thanks Susan! That's a very good point --- it would indeed be more intuitive and flexible for the users if they can generate the masks themselves, than to generate it within RHT using cutoff levels as inputs.
I'll look into implementing this and get back to you!

**Comment by jackieykma** [comment]
Hi Susan, I've changed it to using a cutoff mask instead (as you have suggested).
Essentially, only pixels marked as "True" in the <cutoff_mask> will be considered as possible filament locations (i.e., pixels marked as "False" will be set as "False" in the RHT bitmask)
As before, the default sets this <cutoff_mask> as "None", which will completely turn off this masking functionality

**Comment by seclark** [comment]
This looks great Jackie, thank you!

**Pull request merged**
